### ISSUE TITLE
Show tooltip without clicking the anchor

### ISSUE THREAD

**Issue by CherryPepsi** [skydoves/Orchestra#15]
**Is your feature request related to a problem?**

I am trying to display a tooltip when the anchor is displayed, is there a way to do this without a click event?

**Describe the solution you'd like:**

Please display the tooltip without requiring a click event.

**Comment by skydoves** [comment]
Hey @CherryPepsi,
Of course, you can show up the tooltip with the `balloon.show(anchor)` function.
For getting a view, you may try to wrap your composable function with `AndroidView` following [this guide](https://developer.android.com/jetpack/compose/interop/interop-apis?hl=ko).

**Comment by CherryPepsi** [comment]
Thank you, yes I forgot to close this. I found a way to solve the problem.

Thank you for your quick response!
