### ISSUE TITLE
BalloonAnchor onAnchorClick onLongClick

### ISSUE THREAD

**Issue by ArthurKun021** [skydoves/Orchestra#20]
**Is your feature request related to a problem?**

I would like to only show the balloon once the reference was on longclick, while it passed the function for the click

**Describe the solution you'd like:**

using the combineClickable to enable use the onLongClick

```
modifier = Modifier.combinedClickable(
    onClick = {
        
    },
    onLongClick = {
        
    }
),
```

**Comment by skydoves** [comment]
onAnchorLongClick parameter was added in the new `1.2.0` stable. Thanks!
